name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test

      # Login
      - name: Docker authentication
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
          project_id: cogent-nimbus-389215

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

        # build image
      - name: Build Docker image
        run: docker build -t gcr.io/cogent-nimbus-389215/cockpit:stable .
        env:
          PROJECT_ID: cogent-nimbus-389215
          IMAGE_NAME: cockpit
          TAG: stable

      # build image
      - name: Push Docker image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

#      - name: Push  image to registry
#        run: |
#          echo ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }} | base64 --decode > /tmp/gcp_sa_key.json
#          gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json
#          gcloud auth configure-docker
#          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
