name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test
      - name: Build image
        uses: FlowSquad/docker-cloud-build@v1.0.1
        with:
          gcp-project-id: txenecador-db
          gcp-service-account-key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsupIfJ88lHx1c\nvKavYl4OzrleQTjKl358qmAsb4Isi0X2FiqzRT3ql6Nwiec6+tMY4huQVmeG5X20\n5heWg8K5awBjSscyP69YcPlhWrHL+TOZzjcsiX96fGnbZpwVbvugyhMszH3lm3tA\n8M6Qw5rqOV5kgJtUptjBx/XSJh0Gea7slafo97flUoNkXNLOfHPjoIFfXKMv13BT\naGbyZcdwPL0iY69gvLC2QsIinBaMaoBOpyo+XVwo92WOSyo5r3JDoebR1WhVpF7+\njDsVboJaQcYfJ5FbjqR7ZeoZJbnnUPekgQSamH8CU6Twk3voYirsEdNQZek3XDaK\npxk9dZoRAgMBAAECggEAJ1kbJ3jIohK7/B/HswVsGuBx7uxZtSEcweaIISdH1sDl\nb6FuGceoyrO/mkf4AoIYK796ev+L9vl5kQenkPS0G8wp2vSyexpx5epajRh9j1NW\nM2/8Nqud/DeyX7Y40VMmhGL0SkzNU0x/n/QbgnPk6v2lqKx5difKEh7su3JOQ2Z+\nGFPu3MbLnBO1C98r9puXU91uqHFhbkKxbDNT3MQVkerCSkdotc/n2M6IZXTKZnj6\nF703iDPPV6WyzkOueVRU4x2+qMnxhezh6aEQu03FCSVDXrsQNGO3UdrcO/SC38Gd\nKeSbQZTD7cfideNwe5D34rB1L/eFtqtNQ0mpkY+7dwKBgQDaV6keDB+XK9Hk8n/L\n1AcxLw6WuD2EUiKjflxTrgMDjU0/OTyNV7fa6X2bm6KpObGIVKN5DRzGwBNrbtQM\nesGCvJL1kAnJaR7Milw0gyvG6Eg9nZHJuQjTpsrJgTa59qqx0OKzz/QRBqF0mTMN\nF3MaFb6jUvdNTMH2hp7Rw0smvwKBgQDKhPWbLYT3MATSeg5YeXeEO/6c2WnvrKMi\no5CAoXh59vDTZdPBLNZn/mepADyNbUb0lhnBiy8Mvy70SO+oR0Dj79oBDI9Z9btB\nHZpXT7qyeojgHsZvr/ev5eD1P5YycVTQ6qAa3DfGndf+kRQ0+nTvbE5fBrSD7JL/\neNClu1rDLwKBgBPraW9nVb557fVANm6HEnznOSKA/oPC5owZ7BxqRLYfPwvkkeSn\nOwvKv33hzg44SD0S07MoghaT0XG8s7XLwTnHMHUcxffNElVAzjawPN8xs92DMZjA\nu9BraBbIJhEDMwFz+CrFbxPakgJMM78fA44+q5zE5fD0bsGp+HVUpteLAoGBAJ7e\nLJl93OfYWIAQVb6cEuC9+59pgowM3rCmpQ3zHUJ4MDV1lObeWJed4A2YbOf5CIeI\nVE4a9F7If3oM2UwmEUZ9+oOGKdJFTY7oPRIvLmMicst1+O7WmLP43j8lkZqigwmc\ndNp9VJfPbQh7IOHqc976FITBCszOwgX87ZiFX87rAoGAMnvnEmwMw2zd3bbye8s3\nC5HsL5cD1N7tKgr5gXrX4uLoh7PZzc/iG1SGp9iAPGMMGfmnBfxMUOk6P6xR57me\nRsi9CJV+NyatnNcLPVFTqww+TJYyrsXgTKldVB+5kWphFosMhTEa/gDvBw39BJvu\nn+TtAcJyamAFpfFMKMh/k+Q=\n-----END PRIVATE KEY-----\n"
          image-name: cockpit-stable
          image-sources: Dockerfile
          github-disabled: true
